# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: job_scraper.py

"""
Security Job Alert Scraper — Full 110-Company Edition
======================================================
Runs on GitHub Actions every 6 hours. Completely FREE.
Emails you only NEW security roles with direct clickable links.

Priority in email: Hyderabad > Remote > Bangalore > Other India
Overseas roles (US/UK/EU etc.) are silently dropped.

Install:  pip install requests beautifulsoup4
Secrets:  GMAIL_USER | GMAIL_APP_PASSWORD | GMAIL_RECEIVER
"""

import os, json, re, smtplib, hashlib, time, logging
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.parse import urlparse

import requests
from bs4 import BeautifulSoup

# ─────────────────────────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────────────────────────
EMAIL_CFG = {
    "sender":   os.getenv("GMAIL_USER", ""),
    "password": os.getenv("GMAIL_APP_PASSWORD", ""),
    "to":       os.getenv("GMAIL_RECEIVER", ""),
    "host":     "smtp.gmail.com",
    "port":     587,
}

STATE_FILE        = "seen_jobs.json"
STATE_EXPIRY_DAYS = 60
MAX_WORKERS       = 8
REQUEST_TIMEOUT   = 20

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# KEYWORD MATCHING
# Uses full phrases — far fewer false positives than single words
# ─────────────────────────────────────────────────────────────────────────────
SECURITY_PHRASES = [
    "security engineer", "security analyst", "security architect",
    "security researcher", "security consultant", "security specialist",
    "security manager", "security lead", "security operations",
    "security administrator", "security director", "security officer",
    "security developer", "security advisor", "security head",
    "security principal", "security associate", "security intern",
    "cybersecurity", "cyber security", "information security",
    "cloud security", "application security", "appsec", "cloudsec",
    "network security", "endpoint security", "product security",
    "iam engineer", "iam analyst", "identity engineer", "identity analyst",
    "identity and access", "access management",
    "soc analyst", "soc engineer", "siem engineer", "siem analyst",
    "threat analyst", "threat hunter", "threat intelligence",
    "vulnerability analyst", "vulnerability management", "vulnerability engineer",
    "penetration tester", "pentester", "pen tester",
    "devsecops", "dev sec ops", "incident response",
    "forensics analyst", "malware analyst", "malware researcher",
    "red team", "blue team", "purple team",
    "grc analyst", "grc engineer", "grc consultant",
    "compliance engineer", "risk analyst", "infosec",
    "zero trust", "sast engineer", "dast engineer",
    "offensive security", "defensive security",
]

REJECT_PATTERNS = [
    r"\bphysical security\b", r"\bfood security\b", r"\bnational security\b",
    r"\bsecurity guard\b",    r"\bguard\b",          r"\bsafety officer\b",
    r"\bcredit risk\b",       r"\bmarket risk\b",     r"\boperational risk\b",
    r"\bliquidity risk\b",    r"\bmodel risk\b",      r"\btax compliance\b",
    r"\bhr compliance\b",     r"\bbrand identity\b",  r"\bvisual identity\b",
    r"\baml\b",               r"\banti.money laundering\b",
    r"\bcredit compliance\b", r"\bcorporate identity\b",
]

def is_security_job(title: str) -> bool:
    if not title or len(title) < 6:
        return False
    t = title.lower().strip()
    if not any(p in t for p in SECURITY_PHRASES):
        return False
    return not any(re.search(pat, t, re.IGNORECASE) for pat in REJECT_PATTERNS)

# ─────────────────────────────────────────────────────────────────────────────
# LOCATION SCORING
# ─────────────────────────────────────────────────────────────────────────────
OVERSEAS_SIGNALS = [
    "united states", " usa", "united kingdom", " uk", "london", "canada",
    "australia", "germany", "france", "singapore", "ireland", "poland",
    "romania", "new york", "san francisco", "seattle", "amsterdam",
    "westlake", "southlake", "eden prairie", "guangzhou", "cork",
    ", tx", ", ca", ", wa", ", ny", ", fl", ", ga", ", mn",
]

OTHER_INDIA = [
    "mumbai", "pune", "chennai", "delhi", "noida",
    "gurugram", "gurgaon", "kolkata", "ahmedabad", "kochi", "coimbatore",
]

def score_location(loc: str) -> tuple[int, str]:
    """
    3 = Hyderabad  → top priority
    2 = Remote     → second
    1 = Bangalore  → third
    0 = Other India
   -1 = Overseas   → drop entirely
    """
    s = loc.lower().strip()
    if any(o in s for o in OVERSEAS_SIGNALS):
        return -1, ""
    if "hyderabad" in s or "telangana" in s:
        return 3, "📍 Hyderabad"
    if "remote" in s:
        return 2, "🌐 Remote"
    if "bangalore" in s or "bengaluru" in s:
        return 1, "🏙️ Bangalore"
    if "india" in s or any(c in s for c in OTHER_INDIA):
        return 0, f"🇮🇳 {loc.strip()}" if loc.strip() else "🇮🇳 India"
    # Unknown — keep cautiously
    return 0, f"❓ {loc.strip()}" if loc.strip() else "❓ Unknown"

# ─────────────────────────────────────────────────────────────────────────────
# COMPANY REGISTRY — ALL 110 FROM YOUR ORIGINAL LIST
#
# "greenhouse" → Greenhouse public JSON API  (fast, reliable, no browser)
# "lever"      → Lever public JSON API       (fast, reliable, no browser)
# "html"       → requests + BeautifulSoup    (works for most own-ATS pages)
#
# NOTE: Workday & Eightfold pages are heavily JS-rendered.
#       requests will attempt them but may get limited results.
#       Greenhouse/Lever companies will always work reliably.
# ─────────────────────────────────────────────────────────────────────────────
COMPANIES = {

    # ══ GREENHOUSE — public JSON API, most reliable ═══════════════════════════
    "GitLab":               ("greenhouse", "gitlab"),
    "UiPath":               ("greenhouse", "uipath"),
    "Tide":                 ("greenhouse", "tide"),
    "Freshworks":           ("greenhouse", "freshworks"),
    "Palo Alto Networks":   ("greenhouse", "paloaltonetworks"),
    "CrowdStrike":          ("greenhouse", "crowdstrike"),
    "SentinelOne":          ("greenhouse", "sentinelone"),
    "Cloudflare":           ("greenhouse", "cloudflare"),
    "Elastic":              ("greenhouse", "elastic"),
    "Databricks":           ("greenhouse", "databricks"),
    "MongoDB":              ("greenhouse", "mongodb"),
    "Rubrik":               ("greenhouse", "rubrik"),
    "Druva":                ("greenhouse", "druva"),
    "Postman":              ("greenhouse", "postman"),
    "Browserstack":         ("greenhouse", "browserstack"),
    "Meesho":               ("greenhouse", "meesho"),
    "Sprinklr":             ("greenhouse", "sprinklr"),
    "Darwinbox":            ("greenhouse", "darwinbox"),
    "Wiz":                  ("greenhouse", "wiz-2"),
    "Lacework":             ("greenhouse", "lacework"),
    "Abnormal Security":    ("greenhouse", "abnormalsecurity"),
    "Sysdig":               ("greenhouse", "sysdig"),
    "Aqua Security":        ("greenhouse", "aquasecurity"),
    "Drata":                ("greenhouse", "drata"),
    "Vanta":                ("greenhouse", "vanta"),
    "1Password":            ("greenhouse", "1password"),
    "JumpCloud":            ("greenhouse", "jumpcloud"),
    "PagerDuty":            ("greenhouse", "pagerduty"),
    "New Relic":            ("greenhouse", "newrelic"),
    "Hashicorp":            ("greenhouse", "hashicorp"),
    "Confluent":            ("greenhouse", "confluent"),
    "Chargebee":            ("greenhouse", "chargebee"),
    "Blackbaud":            ("greenhouse", "blackbaud"),

    # ══ LEVER — public JSON API, very reliable ════════════════════════════════
    "Datadog":              ("lever", "datadog"),
    "Snyk":                 ("lever", "snyk"),
    "Razorpay":             ("lever", "razorpay"),
    "Groww":                ("lever", "groww"),
    "PhonePe":              ("lever", "phonepe"),
    "Mattermost":           ("lever", "mattermost"),
    "Whatfix":              ("lever", "whatfix"),

    # ══ HTML — Big Tech ═══════════════════════════════════════════════════════
    "Google": ("html",
        "https://www.google.com/about/careers/applications/jobs/results"
        "?location=Hyderabad%2C+India&has_remote=true&q=security"),
    "Microsoft": ("html",
        "https://apply.careers.microsoft.com/careers?query=security&start=0"
        "&location=Hyderabad%2C++TS%2C++India&sort_by=relevance"
        "&filter_distance=160&filter_include_remote=1"),
    "Meta": ("html",
        "https://www.metacareers.com/jobsearch/?teams[0]=Security"
        "&offices[0]=Hyderabad%2C+India&roles[0]=Full+time+employment"),
    "Apple": ("html",
        "https://jobs.apple.com/en-in/search"
        "?location=india-INDC+hyderabad-HY1&key=security"),
    "Amazon": ("html",
        "https://www.amazon.jobs/en-gb/search?base_query=security"
        "&loc_query=Hyderabad%2C+Telangana%2C+India"
        "&city=Hyderabad&county=Hyderabad&region=Telangana&country=IND"
        "&latitude=17.3949&longitude=78.47081&radius=24km"),
    "GitHub": ("html",
        "https://www.github.careers/careers-home/jobs"
        "?keywords=security&locations=,,India&page=1"),

    # ══ HTML — Semiconductors ═════════════════════════════════════════════════
    "Nvidia": ("html",
        "https://jobs.nvidia.com/careers?query=security&start=0"
        "&location=Hyderabad%2C++Telangana%2C++India"
        "&sort_by=relevance&filter_distance=160&filter_include_remote=1"),
    "Qualcomm": ("html",
        "https://careers.qualcomm.com/careers?query=security&start=0"
        "&location=Hyderabad%2C+TS%2C+India&sort_by=relevance&filter_distance=80"),
    "AMD": ("html",
        "https://careers.amd.com/careers-home/jobs?keywords=security"
        "&location=Hyderabad%2C+Telangana%2C+India&woe=7&regionCode=IN"
        "&stretchUnit=MILES&stretch=10&sortBy=relevance&page=1"),
    "Intel": ("html",
        "https://intel.wd1.myworkdayjobs.com/External"
        "?q=security&locations=1e4a4eb3adf101f44070f976bf8184cf"),
    "Micron Technology": ("html",
        "https://micron.eightfold.ai/careers?domain=micron.com&query=security"
        "&start=0&location=Hyderabad%2C++TS%2C++India"
        "&sort_by=relevance&filter_distance=80&filter_include_remote=1"),
    "Silicon Labs": ("html",
        "https://silabs.wd1.myworkdayjobs.com/SiliconlabsCareers"
        "?q=security&locationCountry=c4f78be1a8f14da0ab49ce1162348a5e"
        "&locations=15081e9a5f8e01a7c343745ac500ce04"),

    # ══ HTML — Enterprise SaaS ════════════════════════════════════════════════
    "Salesforce": ("html",
        "https://www.salesforce.com/company/careers/jobs/"
        "?location=Hyderabad&search=security&page=1"),
    "ServiceNow": ("html",
        "https://careers.servicenow.com/jobs/?search=security"
        "&country=India&region=Telangana&location=Hyderabad&origin=global"),
    "Atlassian": ("html",
        "https://www.atlassian.com/company/careers/all-jobs"
        "?team=Security&location=India&search="),
    "Adobe": ("html",
        "https://adobe.wd5.myworkdayjobs.com/external_experienced"
        "?q=security&locationCountry=IN"),
    "Oracle": ("html",
        "https://careers.oracle.com/en/sites/jobsearch/jobs?keyword=security"
        "&location=HYDERABAD%2C+TELANGANA%2C+India"
        "&locationId=300001842985230&locationLevel=city&mode=location"
        "&radius=25&radiusUnit=MI"),
    "SAP": ("html",
        "https://jobs.sap.com/search/?createNewAlert=false"
        "&q=security&locationsearch=Hyderabad"),
    "VMware/Broadcom": ("html",
        "https://careers.broadcom.com/jobs?q=security+cybersecurity"
        "&location=Hyderabad%2C+Telangana%2C+India"),
    "Pegasystems": ("html",
        "https://www.pega.com/about/careers/search?q=security&location=Hyderabad"),
    "Zoho": ("html",
        "https://careers.zohocorp.com/jobs/Careers?search=security"),
    "Intuit": ("html",
        "https://jobs.intuit.com/search-jobs/security/India/27595/1/2/1269750/22/79/0/2"),
    "Gainsight": ("html",
        "https://gainsight.wd5.myworkdayjobs.com/Gainsight_External_Careers"
        "?q=security&locations=e33bd8017cf71001bd06d95a7e730000"),

    # ══ HTML — Cybersecurity ══════════════════════════════════════════════════
    "Zscaler": ("html",
        "https://www.zscaler.com/careers/search?q=security&office=india"),
    "Sophos": ("html",
        "https://jobs.sophos.com/search?q=security&l=Hyderabad"),
    "Akamai": ("html",
        "https://www.akamai.com/careers/job-search?q=security&location=India"),

    # ══ HTML — Networking / Infra ═════════════════════════════════════════════
    "Cisco": ("html",
        "https://careers.cisco.com/global/en/search-results?keywords=security"),
    "Splunk": ("html",
        "https://jobs.cisco.com/jobs/SearchJobs/splunk%20security"
        "?listFilterMode=1&21178=21178"),
    "F5": ("html",
        "https://www.f5.com/company/careers/open-positions?q=security&country=India"),

    # ══ HTML — Cloud / Data ═══════════════════════════════════════════════════
    "Snowflake": ("html",
        "https://careers.snowflake.com/us/en/search-results"
        "?keywords=security&country=India"),
    "DigitalOcean": ("html",
        "https://www.digitalocean.com/careers/open-roles"
        "?query=security&location=Hyderabad"),
    "Nutanix": ("html",
        "https://careers.nutanix.com/en/jobs/?search=security&pagesize=20#results"),

    # ══ HTML — Financial Services ═════════════════════════════════════════════
    "Goldman Sachs": ("html",
        "https://higher.gs.com/results?JOB_FUNCTION=Security+Engineering"
        "&LOCATION=Hyderabad&page=1&search=security&sort=RELEVANCE"),
    "JPMorgan": ("html",
        "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs"
        "?keyword=security&location=Hyderabad%2C+Telangana%2C+India"
        "&locationId=300000081155702&locationLevel=city&mode=location"
        "&radius=25&radiusUnit=MI"),
    "Morgan Stanley": ("html",
        "https://morganstanley.eightfold.ai/careers?source=mscom&query=security"
        "&start=0&sort_by=relevance&filter_city=Mumbai%2CBengaluru"),
    "HSBC": ("html",
        "https://portal.careers.hsbc.com/careers?query=Cybersecurity"
        "&location=India&domain=hsbc.com&sort_by=relevance"),
    "Wells Fargo": ("html",
        "https://www.wellsfargojobs.com/en/jobs/"
        "?search=security&location=HYDERABAD&pagesize=20#results"),
    "Vanguard": ("html",
        "https://www.vanguardjobs.com/job-search-results/"
        "?location=IN%2C+Telangana%2C+Hyderabad&keyword=cybersecurity"
        "&category[]=Technology"),
    "Invesco": ("html",
        "https://invesco.wd1.myworkdayjobs.com/en-GB/IVZ"
        "?q=security&locations=1804888b7f5a100128e426fb60bc0000"),
    "FactSet": ("html",
        "https://www.factset.com/careers/job-search?q=security&l=Hyderabad"),
    "State Street": ("html",
        "https://careers.statestreet.com/global/en/search-results?m=3"
        "&keywords=security&cityStateCountry=Hyderabad%2C+Telangana%2C+India"),
    "Synchrony": ("html",
        "https://www.synchrony.com/careers/job-search.html"
        "?q=security&location=Hyderabad"),
    "Broadridge": ("html",
        "https://www.broadridge.com/careers/search-jobs?q=security&l=India"),
    "Stripe": ("html",
        "https://stripe.com/jobs/search?query=security"),
    "LSEG": ("html",
        "https://lseg.wd3.myworkdayjobs.com/Careers?q=security"
        "&locationCountry=c4f78be1a8f14da0ab49ce1162348a5e"
        "&primaryLocation=85fcb4c116cc1001ed602e25ce830000"),

    # ══ HTML — IT Services ════════════════════════════════════════════════════
    "IBM": ("html",
        "https://www.ibm.com/in-en/careers/search"
        "?field_keyword_08[0]=Security&field_keyword_05[0]=India"),
    "Wipro": ("html",
        "https://careers.wipro.com/careers-home/jobs?q=security"
        "&location=Hyderabad%2C+Telangana%2C+India"),
    "Infosys": ("html",
        "https://career.infosys.com/joblist"
        "?industryType=j&location=Hyderabad&skills=security"),
    "TCS": ("html",
        "https://www.tcs.com/careers/india/job-search"
        "?keyword=security&location=Hyderabad"),
    "HCLTech": ("html",
        "https://www.hcltech.com/careers/job-search"
        "?keyword=security&location=Hyderabad"),
    "Accenture": ("html",
        "https://www.accenture.com/in-en/careers/jobsearch"
        "?jq=security&jl=Hyderabad"),
    "Capgemini": ("html",
        "https://www.capgemini.com/in-en/careers/job-search/"
        "?search_term=security&country=India&city=Hyderabad"),
    "Deloitte": ("html",
        "https://apply.deloitte.com/careers/SearchJobs/security"
        "?3836=[India]&listFilterMode=1"),
    "NTT": ("html",
        "https://services.global.ntt/en-us/careers?q=security&location=Hyderabad"),
    "EPAM": ("html",
        "https://www.epam.com/careers/job-listings?search=security&city=Hyderabad"),
    "Accolite": ("html",
        "https://accolite.com/careers/?search=security"),

    # ══ HTML — Telecom ════════════════════════════════════════════════════════
    "AT&T": ("html",
        "https://www.att.jobs/search-jobs/security/Hyderabad%2C+Telangana/117/1/4"
        "/1269750-1254788-1269844-1269843/17x38405/78x45636/50/2"),
    "Ericsson": ("html",
        "https://jobs.ericsson.com/careers?query=security"
        "&location=Hyderabad%2C+Telangana%2C+India"),
    "Verizon": ("html",
        "https://verizon.wd5.myworkdayjobs.com/verizon_careers"
        "?q=security&locationCountry=IN"),
    "T-Mobile": ("html",
        "https://careers.t-mobile.com/search-jobs/security/Hyderabad/562/1/2"
        "/6252001/17.385/78.4867/50/2"),

    # ══ HTML — Fintech ════════════════════════════════════════════════════════
    "GoDaddy": ("html",
        "https://careers.godaddy.com/jobs/search"
        "?page=1&query=security&country_codes[]=IN"),

    # ══ HTML — Retail / Consumer ══════════════════════════════════════════════
    "Walmart": ("html",
        "https://careers.walmart.com/results"
        "?q=security&l=Hyderabad%2C+Telangana%2C+India"),
    "Costco": ("html",
        "https://careers.costco.com/jobs?keywords=security&stretchUnit=MILES"
        "&stretch=10&location=Hyderabad%2C+Telangana%2C+India&woe=7&regionCode=IN"),
    "Flipkart": ("html",
        "https://www.flipkartcareers.com/#!/joblist?search=security"),
    "PepsiCo": ("html",
        "https://www.pepsicojobs.com/main/jobs?keywords=security"
        "&stretchUnit=MILES&stretch=10&location=Hyderabad%2C+Telangana%2C+India"
        "&woe=7&regionCode=IN"),
    "McDonald's": ("html",
        "https://careers.mcdonalds.com/jobs?filter[country][0]=IN"
        "&keyword=security&location_name=hyderabad&location_type=1"),

    # ══ HTML — Industrial / Hardware ══════════════════════════════════════════
    "Honeywell": ("html",
        "https://careers.honeywell.com/en/sites/Honeywell/jobs?keyword=security"
        "&location=Hyderabad%2C+Telangana%2C+India"
        "&locationId=100000013406729&locationLevel=city&mode=location"
        "&radius=25&radiusUnit=MI"),
    "Bosch": ("html",
        "https://jobs.bosch.com/job-search-result/?language=en"
        "&q=security&country=India&city=Hyderabad"),
    "ABB": ("html",
        "https://new.abb.com/jobs/search?q=security&location=India"),
    "Siemens": ("html",
        "https://jobs.siemens.com/careers?query=security"
        "&location=Hyderabad%2C+Telangana%2C+India"),
    "Schneider Electric": ("html",
        "https://www.se.com/in/en/about-us/careers/job-search.jsp"
        "?text=security&country=India&city=Hyderabad"),

    # ══ HTML — Other Tech / Media ═════════════════════════════════════════════
    "Uber": ("html",
        "https://www.uber.com/in/en/careers/list/"
        "?query=security&location=IND-Telangana-Hyderabad"),
    "FedEx": ("html",
        "https://www.fedex.com/en-us/about/careers.html?q=security&location=India"),
    "Eli Lilly": ("html",
        "https://careers.lilly.com/global/en/search-results"
        "?keywords=security&location=Hyderabad%2C+Telangana%2C+India"),
    "Novartis": ("html",
        "https://www.novartis.com/in-en/careers/career-search"
        "?search_api_fulltext=cyber+security&country[]=LOC_IN"
        "&field_job_posted_date=All&op=Submit"),
    "WBD": ("html",
        "https://careers.wbd.com/global/en/hyderabad-jobs/search-results"
        "?keywords=security"),
    "Providence": ("html",
        "https://careers.providence.in/search/"
        "?q=&q2=&alertId=&title=security&location=&date=#searchresults"),
    "Electronic Arts": ("html",
        "https://jobs.ea.com/en_US/careers/Home/Hyderabad"
        "?4536=[8317]&4536_format=3019&listFilterMode=1&jobRecordsPerPage=20"),
    "Straive": ("html",
        "https://straive.com/careers/?search=security"),
    "Western Union": ("html",
        "https://careers.westernunion.com/global/en/search-results"
        "?keywords=security&location=Hyderabad%2C+Telangana%2C+India"),

    # ══ HTML — Banking ════════════════════════════════════════════════════════
    "Bank of America": ("html",
        "https://careers.bankofamerica.com/en-us/job-search"
        "?search=security&city=Hyderabad&country=India"),
    "Barclays": ("html",
        "https://search.jobs.barclays/search-jobs/security/Hyderabad/461/1/2"
        "/6252001/17.3850/78.4867/50/2"),
    "BNY Mellon": ("html",
        "https://bnymellon.wd1.myworkdayjobs.com/BNYMellon"
        "?q=security&locationCountry=IN"),
    "Citi": ("html",
        "https://jobs.citi.com/search-jobs/security/Hyderabad/287/2"
        "/6252001/17.385/78.4867/50/2"),
    "UBS": ("html",
        "https://jobs.ubs.com/TGnewUI/Search/home/HomeWithPreLoad"
        "?partnerid=25008&siteid=5012&q=security&locationsearch=Hyderabad"),
    "US Bank": ("html",
        "https://careers.usbank.com/global/en/search-results"
        "?keywords=security&location=Hyderabad%2C+Telangana%2C+India"),
    "Franklin Templeton": ("html",
        "https://careers.franklintempleton.com/global/en/search-results"
        "?keywords=security&location=Hyderabad"),
    "Fiserv": ("html",
        "https://fiserv.wd5.myworkdayjobs.com/EXT_Careers"
        "?q=security&locationCountry=IN"),
    "Charles Schwab": ("html",
        "https://schwabjobs.com/search-jobs/security/Hyderabad/271/1/2"
        "/6252001/17.385/78.4867/50/2"),
    "DBS Bank": ("html",
        "https://www.dbs.com/careers/job-search?keyword=security&location=Hyderabad"),
    "Lloyds Banking Group": ("html",
        "https://lloydsbankinggroupcareers.com/search/?q=security&l=Hyderabad"),
    "MetLife": ("html",
        "https://careers.metlife.com/global/en/search-results"
        "?keywords=security&location=Hyderabad%2C+Telangana%2C+India"),
    "Moody's": ("html",
        "https://careers.moodys.com/us/en/search-results"
        "?keywords=security&location=Hyderabad"),
    "S&P Global": ("html",
        "https://careers.spglobal.com/jobs"
        "?keywords=security&location=Hyderabad%2C+Telangana%2C+India"),
    "Voya Financial": ("html",
        "https://voya.wd5.myworkdayjobs.com/Voya_Careers"
        "?q=security&locationCountry=IN"),
    "Nationwide": ("html",
        "https://nationwide.jobs/hyderabad-in/jobs/?q=security"),
    "LPL Financial": ("html",
        "https://careers.lpl.com/search-jobs/security/Hyderabad/472/1/2"
        "/6252001/17.385/78.4867/50/2"),

    # ══ HTML — More Tech ══════════════════════════════════════════════════════
    "Dell Technologies": ("html",
        "https://jobs.dell.com/search-jobs/security/Hyderabad/507/1/2"
        "/6252001/17.385/78.4867/50/2"),
    "Texas Instruments": ("html",
        "https://careers.ti.com/search-jobs/security/India/120/1/2"
        "/6252001/17.385/78.4867/50/2"),
    "Persistent Systems": ("html",
        "https://www.persistent.com/careers/job-search/"
        "?keyword=security&location=Hyderabad"),
    "Hexaware Technologies": ("html",
        "https://hexaware.com/careers/job-search/?q=security&location=Hyderabad"),
    "OpenText": ("html",
        "https://careers.opentext.com/global/en/search-results"
        "?keywords=security&location=Hyderabad%2C+Telangana%2C+India"),
    "Red Hat": ("html",
        "https://jobs.redhat.com/search-jobs/security/Hyderabad/506/1/2"
        "/6252001/17.385/78.4867/50/2"),
    "Garmin": ("html",
        "https://careers.garmin.com/careers-home/jobs"
        "?q=security&l=Hyderabad%2C+India"),

    # ══ HTML — Healthcare / Pharma ════════════════════════════════════════════
    "Optum (UnitedHealth)": ("html",
        "https://careers.unitedhealthgroup.com/search-jobs/security/Hyderabad/523/1/2"
        "/6252001/17.385/78.4867/50/2"),
    "Elevance Health": ("html",
        "https://elevancehealth.wd1.myworkdayjobs.com/elevancehealth"
        "?q=security&locationCountry=IN"),
    "Thermo Fisher": ("html",
        "https://jobs.thermofisher.com/global/en/search-results"
        "?keywords=security&location=Hyderabad%2C+Telangana%2C+India"),
    "Johnson & Johnson": ("html",
        "https://careers.jnj.com/en/jobs/"
        "?search=security&location=Hyderabad%2C+Telangana%2C+India"),
    "Medtronic": ("html",
        "https://jobs.medtronic.com/jobs"
        "?keywords=security&location=Hyderabad%2C+Telangana%2C+India"),
    "Philips": ("html",
        "https://careers.philips.com/global/en/search-results"
        "?keywords=security&location=Hyderabad%2C+Telangana%2C+India"),
    "Roche": ("html",
        "https://careers.roche.com/global/en/search-results"
        "?keywords=security&location=Hyderabad%2C+Telangana%2C+India"),
    "Sanofi": ("html",
        "https://www.sanofi.com/en/careers/job-search"
        "?keyword=security&location=Hyderabad"),

    # ══ HTML — Aerospace / Industrial ═════════════════════════════════════════
    "Nike": ("html",
        "https://careers.nike.com/jobs?query=security&location=Hyderabad%2C+India"),
    "Boeing": ("html",
        "https://jobs.boeing.com/search-jobs/security/Hyderabad/440/1/2"
        "/6252001/17.385/78.4867/50/2"),
}

# ─────────────────────────────────────────────────────────────────────────────
# STATE — deduplication (persisted in seen_jobs.json in your repo)
# ─────────────────────────────────────────────────────────────────────────────
def load_state() -> dict:
    if not Path(STATE_FILE).exists():
        return {}
    try:
        with open(STATE_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        cutoff = datetime.now() - timedelta(days=STATE_EXPIRY_DAYS)
        return {
            k: v for k, v in data.items()
            if datetime.fromisoformat(
                v.get("seen_at", "2000-01-01")
            ) > cutoff
        }
    except Exception:
        return {}

def save_state(state: dict) -> None:
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)

def make_id(company: str, title: str, url: str) -> str:
    return hashlib.md5(f"{company}|{title}|{url}".encode()).hexdigest()

# ─────────────────────────────────────────────────────────────────────────────
# SCRAPERS
# ─────────────────────────────────────────────────────────────────────────────
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
}

def fetch_greenhouse(company: str, token: str) -> list[dict]:
    url = f"https://boards-api.greenhouse.io/v1/boards/{token}/jobs?content=true"
    try:
        r = requests.get(url, headers=HEADERS, timeout=REQUEST_TIMEOUT)
        r.raise_for_status()
        out = []
        for item in r.json().get("jobs", []):
            title = item.get("title", "").strip()
            if not is_security_job(title):
                continue
            loc          = item.get("location", {}).get("name", "") or ""
            score, badge = score_location(loc)
            if score < 0:
                continue
            out.append({
                "company": company,
                "title":   title,
                "badge":   badge,
                "score":   score,
                "url":     item.get("absolute_url", ""),
                "posted":  item.get("updated_at", "")[:10],
            })
        return out
    except Exception as e:
        log.warning(f"  Greenhouse [{company}]: {e}")
        return []

def fetch_lever(company: str, token: str) -> list[dict]:
    url = f"https://api.lever.co/v0/postings/{token}?mode=json"
    try:
        r = requests.get(url, headers=HEADERS, timeout=REQUEST_TIMEOUT)
        r.raise_for_status()
        out = []
        for item in r.json():
            title = item.get("text", "").strip()
            if not is_security_job(title):
                continue
            loc          = item.get("categories", {}).get("location", "") or ""
            score, badge = score_location(loc)
            if score < 0:
                continue
            ts     = item.get("createdAt", 0)
            posted = datetime.fromtimestamp(ts / 1000).strftime("%Y-%m-%d") if ts else ""
            out.append({
                "company": company,
                "title":   title,
                "badge":   badge,
                "score":   score,
                "url":     item.get("hostedUrl", ""),
                "posted":  posted,
            })
        return out
    except Exception as e:
        log.warning(f"  Lever [{company}]: {e}")
        return []

def _clean(raw: str) -> str:
    """Strip trailing metadata noise from scraped anchor text."""
    for sep in [
        " · ", " - India", " – India", "Hyderabad,", "Bangalore,",
        "Telangana,", " Posted", "Full-time", "Save for Later",
        "Requisition", " [L", "\u00b7", "\u2014",
    ]:
        raw = raw.split(sep)[0]
    return raw.strip(" ,.-\t\n\r")

def _extract_loc(text: str) -> str:
    """Pull a location string from a block of text."""
    for pat in [
        r"Hyderabad[,\s]+(?:Telangana[,\s]+)?India",
        r"(?:Bengaluru|Bangalore)[,\s]+(?:Karnataka[,\s]+)?India",
        r"(?:Mumbai|Pune|Chennai|Delhi|Noida|Gurugram)[,\s]+India",
        r"\bRemote\b",
        r"\bIndia\b",
    ]:
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            return m.group(0).strip()
    return ""

def fetch_html(company: str, url: str) -> list[dict]:
    """
    requests + BeautifulSoup.
    Works for static/SSR pages.
    Workday/Eightfold are JS-heavy — may return empty (that's normal).
    """
    try:
        r = requests.get(url, headers=HEADERS, timeout=REQUEST_TIMEOUT)
        r.raise_for_status()
    except Exception as e:
        log.warning(f"  HTML fetch [{company}]: {e}")
        return []

    try:
        soup = BeautifulSoup(r.text, "html.parser")
        for tag in soup(["script", "style", "nav", "footer", "header", "noscript"]):
            tag.decompose()

        page_text = soup.get_text(" ", strip=True)
        found     = {}   # title → (job_url, loc_string)

        # Pass 1 — anchor tags with hrefs (job links are almost always <a>)
        for a in soup.find_all("a", href=True):
            title = _clean(a.get_text(strip=True))
            if not is_security_job(title) or title in found:
                continue
            href = a["href"]
            if href.startswith("http"):
                job_url = href
            elif href.startswith("/"):
                parsed  = urlparse(url)
                job_url = f"{parsed.scheme}://{parsed.netloc}{href}"
            else:
                job_url = url
            parent     = a.find_parent()
            ctx        = parent.get_text(" ", strip=True) if parent else ""
            loc        = _extract_loc(ctx) or _extract_loc(page_text)
            found[title] = (job_url, loc)

        # Pass 2 — headings + list items if Pass 1 got nothing
        if not found:
            for tag in soup.find_all(["h1", "h2", "h3", "h4", "li"]):
                title = _clean(tag.get_text(strip=True))
                if not is_security_job(title) or title in found:
                    continue
                loc = _extract_loc(tag.get_text(" ")) or _extract_loc(page_text)
                found[title] = (url, loc)

        today = datetime.today().strftime("%Y-%m-%d")
        out   = []
        for title, (job_url, loc) in list(found.items())[:50]:
            score, badge = score_location(loc)
            if score < 0:
                continue
            out.append({
                "company": company
